# Página Inicial {.unnumbered}

Seja bem-vindo(a) ao livro "Uma Introdução à Computação com Julia". Este livro reúne as notas de aula da disciplina MAC0115 - Introdução à Computação para Ciências Exatas e Tecnologia. Com linguagem simples e objetiva, o livro apresenta os principais conceitos de programação, complementados por exemplos práticos de código.

Esta disciplina visa introduzir os fundamentos da computação através de um percurso histórico até conceitos práticos de programação utilizando a linguagem Julia. Cobre algoritmos, arquitetura de computadores, linguagens algorítmicas (com expressões, comandos, estruturas de dados e funções), metodologias de desenvolvimento e boas práticas de programação, além de proporcionar uma extensa prática de programação e depuração, formando uma base técnica completa para iniciantes.

O livro está sendo atualizado juntamente com a disciplina. Podem ocorrer mudanças na ordem e nos exemplos, mas nada que afete o conteúdo ministrado. Não se preocupe se algo não estiver exatamente onde você esperava encontrar.